name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watch=false

      - name: Build production frontend
        run: npm run build

      - name: Build production frontend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::133358351513:role/K12InfoGitHubDeployRole
          aws-region: us-west-2
          allowed-account-ids: 133358351513

      - name: Deploy frontend to S3
        run: |
          aws s3 sync \
            dist/frontend/browser/ \
            s3://k12info-frontend-prod \
            --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EUTOJG23EEYG \
            --paths "/*"